Dry run

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,4 +1,4 @@
-name: Build / Test / Publish
+name: Build, Test, Publish
 
 on:
   pull_request:
@@ -113,10 +113,6 @@ jobs:
         with:
           cmd: prepublish
 
-      - name: Show workspace contents
-        run: |
-          ls -R .
-
       - name: Prepare version for publish
         id: prep
         run: |
@@ -143,5 +139,12 @@ jobs:
 
       - name: Publish to npm
         run: |
-          npm version $NEW_VERSION
-          npm publish --tag dev
+          if ! git diff-index --quiet HEAD --; then
+            echo "Directory is not clean. Listing changes:"
+            git status
+            exit 1  # Optional: Fail the step explicitly to avoid proceeding
+          else
+            echo "Directory is clean. Proceeding with npm version and publish."
+            npm version $NEW_VERSION
+            yarn publish --tag dev --dry-run
+          fi
