Should try to pulbish regardless of unlcean dir

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -139,5 +139,16 @@ jobs:
 
       - name: Publish to npm
         run: |
-          npm version $NEW_VERSION
-          yarn publish --tag dev --dry-run
+          # Listing changes without failing the job
+          if ! git diff-index --quiet HEAD --; then
+            echo "Directory is not clean. Listing changes:"
+            git status
+          else
+            echo "Directory is clean."
+          fi
+          
+          # Proceeding with npm version and yarn publish
+          # This includes all files in the current directory, including untracked ones
+          echo "Publishing to npm with untracked changes..."
+          npm version $NEW_VERSION --no-git-tag-version
+          yarn publish --tag dev --no-commit-hooks --non-interactive --dry-run
